# Generated by Django 5.2.8 on 2025-11-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='notificatio_recipie_fe19f0_idx',
            old_name='emaillog_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='notificatio_status_18a272_idx',
            old_name='emaillog_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a972ce_idx',
            old_name='notificatio_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_idx2',
        ),
    ]
