# Generated by Django 5.2.6 on 2025-11-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctorprofile_availability_rules_doctorclinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_name',
        ),
    ]
